check50: 
  checks: __init__.py
  files: &check50_files
    - !exclude "*"
    - !include "assignment1*.py"
    # assignment1:
    #   - run: python3 assignment1.py hello_world
    #     stdout: 
    #     - |- 
    #       Hello
    #       *****
    #       World
    #     - |-
    #       Hello
    #            *****
    #                 World
    #     - 50
    #     - Hello World
    #     - 10.0
    #     - The earth is round!\n
    #     exit: 0
